log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-rke2r0
      # renovate: datasource=github-tags depName=rancher/rke2 versioning=regex:^v(?<major>1)\.(?<minor>33)\.(?<patch>\d+)\+rke2r(?<build>\d+)$
      rke2_version: v1.33.10+rke2r1
      rke2_sha_amd64: 689d8ce546480282750162b7a6b4a1fe5dfbb3588786cd9e625d8bd186d10f9e
      rke2_sha_arm64: 7f2c3506c9178121e729d7090d179cda6f43c6fe5c2081051dc10bcde0bc1662
